process.env.DATABASE_URL = '<YOUR-POSTGRES-URI>';
process.env.AWS_ACCESS_KEY_ID = '<ACCESS-KEY>';
process.env.AWS_SECRET_ACCESS_KEY = '<SECRET-KEY>';
process.env.MAILGUN_API_KEY = '<MAILGUN_API_KEY>';
